# Demonstation of the neigbor search operation

In [1]:
import torch as pt
from torch.utils.cpp_extension import load

## Compile of the kernel

In [2]:
load(name='neighbors', sources=['neighbors.cpp', 'neighbors_cuda.cu'], is_python_module=False)
get_neighbor_list = pt.ops.neighbors.get_neighbor_list

## Run the operation

In [3]:
pos = pt.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]], device='cuda')
get_neighbor_list(pos)

(tensor([0, 0, 1, 1, 2, 2], device='cuda:0', dtype=torch.int32),
 tensor([1, 2, 0, 2, 0, 1], device='cuda:0', dtype=torch.int32),
 tensor([ 5.1962, 10.3923,  5.1962,  5.1962, 10.3923,  5.1962], device='cuda:0'))